package main

import (
	"github.com/zoom-api/mcp-server/config"
	"github.com/zoom-api/mcp-server/models"
	tools_phone "github.com/zoom-api/mcp-server/tools/phone"
	tools_webinars "github.com/zoom-api/mcp-server/tools/webinars"
	tools_dashboards "github.com/zoom-api/mcp-server/tools/dashboards"
	tools_contacts "github.com/zoom-api/mcp-server/tools/contacts"
	tools_cloud_recording "github.com/zoom-api/mcp-server/tools/cloud_recording"
	tools_phone_devices "github.com/zoom-api/mcp-server/tools/phone_devices"
	tools_phone_auto_receptionists "github.com/zoom-api/mcp-server/tools/phone_auto_receptionists"
	tools_reports "github.com/zoom-api/mcp-server/tools/reports"
	tools_roles "github.com/zoom-api/mcp-server/tools/roles"
	tools_accounts "github.com/zoom-api/mcp-server/tools/accounts"
	tools_meetings "github.com/zoom-api/mcp-server/tools/meetings"
	tools_billing "github.com/zoom-api/mcp-server/tools/billing"
	tools_chat_messages "github.com/zoom-api/mcp-server/tools/chat_messages"
	tools_phone_shared_line_groups "github.com/zoom-api/mcp-server/tools/phone_shared_line_groups"
	tools_groups "github.com/zoom-api/mcp-server/tools/groups"
	tools_rooms "github.com/zoom-api/mcp-server/tools/rooms"
	tools_rooms_account "github.com/zoom-api/mcp-server/tools/rooms_account"
	tools_sip_connected_audio "github.com/zoom-api/mcp-server/tools/sip_connected_audio"
	tools_im_chat "github.com/zoom-api/mcp-server/tools/im_chat"
	tools_sip_phone "github.com/zoom-api/mcp-server/tools/sip_phone"
	tools_users "github.com/zoom-api/mcp-server/tools/users"
	tools_im_groups "github.com/zoom-api/mcp-server/tools/im_groups"
	tools_tsp "github.com/zoom-api/mcp-server/tools/tsp"
	tools_devices "github.com/zoom-api/mcp-server/tools/devices"
	tools_phone_blocked_list "github.com/zoom-api/mcp-server/tools/phone_blocked_list"
	tools_rooms_location "github.com/zoom-api/mcp-server/tools/rooms_location"
	tools_chat_channels "github.com/zoom-api/mcp-server/tools/chat_channels"
	tools_chatbot_messages "github.com/zoom-api/mcp-server/tools/chatbot_messages"
	tools_phone_call_queues "github.com/zoom-api/mcp-server/tools/phone_call_queues"
	tools_rooms_devices "github.com/zoom-api/mcp-server/tools/rooms_devices"
	tools_trackingfield "github.com/zoom-api/mcp-server/tools/trackingfield"
	tools_phone_site "github.com/zoom-api/mcp-server/tools/phone_site"
	tools_deprecated_api_endpoints "github.com/zoom-api/mcp-server/tools/deprecated_api_endpoints"
	tools_chat_channels_account_level "github.com/zoom-api/mcp-server/tools/chat_channels_account_level"
	tools_phone_reports "github.com/zoom-api/mcp-server/tools/phone_reports"
	tools_common_area_phones "github.com/zoom-api/mcp-server/tools/common_area_phones"
	tools_pac "github.com/zoom-api/mcp-server/tools/pac"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_phone.CreateGetphonenumberdetailsTool(cfg),
		tools_phone.CreateUpdatephonenumberdetailsTool(cfg),
		tools_webinars.CreateWebinarregistrantstatusTool(cfg),
		tools_dashboards.CreateListmeetingsatisfactionTool(cfg),
		tools_contacts.CreateGetusercontactsTool(cfg),
		tools_dashboards.CreateDashboardwebinarparticipantsTool(cfg),
		tools_dashboards.CreateParticipantfeedbackTool(cfg),
		tools_cloud_recording.CreateRecordingslistTool(cfg),
		tools_cloud_recording.CreateRecordinggetTool(cfg),
		tools_cloud_recording.CreateRecordingdeleteTool(cfg),
		tools_webinars.CreateDeletewebinarregistrantTool(cfg),
		tools_webinars.CreateWebinarregistrantgetTool(cfg),
		tools_dashboards.CreateGetcalllogmetricsdetailsTool(cfg),
		tools_phone_devices.CreateListphonedevicesTool(cfg),
		tools_phone_devices.CreateAddphonedeviceTool(cfg),
		tools_phone_auto_receptionists.CreateUnassignaphonenumautoreceptionistTool(cfg),
		tools_cloud_recording.CreateGetaccountcloudrecordingTool(cfg),
		tools_reports.CreateReportmeetingparticipantsTool(cfg),
		tools_roles.CreateCreateroleTool(cfg),
		tools_roles.CreateRolesTool(cfg),
		tools_accounts.CreateAccountmanageddomainTool(cfg),
		tools_reports.CreateReportmeetingpollsTool(cfg),
		tools_meetings.CreateMeetingpollupdateTool(cfg),
		tools_meetings.CreateMeetingpolldeleteTool(cfg),
		tools_meetings.CreateMeetingpollgetTool(cfg),
		tools_billing.CreateAccountplansTool(cfg),
		tools_billing.CreateAccountplancreateTool(cfg),
		tools_phone.CreateGetsettingtemplateTool(cfg),
		tools_phone.CreateUpdatesettingtemplateTool(cfg),
		tools_meetings.CreateMeetingregistrantdeleteTool(cfg),
		tools_phone.CreateUnassignphonenumberTool(cfg),
		tools_meetings.CreateListmeetingtemplatesTool(cfg),
		tools_chat_messages.CreateGetchatmessagesTool(cfg),
		tools_chat_messages.CreateSendachatmessageTool(cfg),
		tools_dashboards.CreateDashboardmeetingdetailTool(cfg),
		tools_phone_shared_line_groups.CreateDeleteamemberslgTool(cfg),
		tools_groups.CreateUpdateagroupmemberTool(cfg),
		tools_groups.CreateGroupmembersdeleteTool(cfg),
		tools_cloud_recording.CreateMeetingrecordingregistrantstatusTool(cfg),
		tools_rooms.CreateListzrdevicesTool(cfg),
		tools_rooms_account.CreateGetzraccountprofileTool(cfg),
		tools_rooms_account.CreateUpdatezraccprofileTool(cfg),
		tools_rooms.CreateListzoomroomsTool(cfg),
		tools_rooms.CreateAddaroomTool(cfg),
		tools_sip_connected_audio.CreateListinternalnumbersTool(cfg),
		tools_sip_connected_audio.CreateAddinternalnumbersTool(cfg),
		tools_im_chat.CreateSendimmessagesTool(cfg),
		tools_chat_messages.CreateDeletechatmessageTool(cfg),
		tools_chat_messages.CreateEditmessageTool(cfg),
		tools_sip_connected_audio.CreateDeletesiptrunkTool(cfg),
		tools_dashboards.CreateDashboardzoomroomsTool(cfg),
		tools_dashboards.CreateDashboardmeetingparticipantqosTool(cfg),
		tools_sip_phone.CreateListsipphonesTool(cfg),
		tools_sip_phone.CreateCreatesipphoneTool(cfg),
		tools_users.CreateSwitchuseraccountTool(cfg),
		tools_webinars.CreateListpastwebinarpollresultsTool(cfg),
		tools_im_groups.CreateImgroupsTool(cfg),
		tools_im_groups.CreateImgroupcreateTool(cfg),
		tools_rooms.CreateUpdateroomprofileTool(cfg),
		tools_rooms.CreateDeleteazoomroomTool(cfg),
		tools_rooms.CreateGetzrprofileTool(cfg),
		tools_tsp.CreateUsertspdeleteTool(cfg),
		tools_tsp.CreateUsertspTool(cfg),
		tools_tsp.CreateUsertspupdateTool(cfg),
		tools_im_groups.CreateImgroupdeleteTool(cfg),
		tools_im_groups.CreateImgroupTool(cfg),
		tools_im_groups.CreateImgroupupdateTool(cfg),
		tools_meetings.CreateMeetinglivestreamstatusupdateTool(cfg),
		tools_rooms.CreateChangezrlocationTool(cfg),
		tools_phone.CreateDeleteusersettingTool(cfg),
		tools_phone.CreateUpdateusersettingTool(cfg),
		tools_phone.CreateAddusersettingTool(cfg),
		tools_users.CreateUpdatepresencestatusTool(cfg),
		tools_phone_auto_receptionists.CreateUnassignallphonenumsautoreceptionistTool(cfg),
		tools_phone_auto_receptionists.CreateAssignphonenumbersautoreceptionistTool(cfg),
		tools_reports.CreateReportoperationlogsTool(cfg),
		tools_phone_shared_line_groups.CreateGetasharedlinegroupTool(cfg),
		tools_phone_shared_line_groups.CreateUpdateasharedlinegroupTool(cfg),
		tools_phone_shared_line_groups.CreateDeleteasharedlinegroupTool(cfg),
		tools_dashboards.CreateDashboardwebinardetailTool(cfg),
		tools_dashboards.CreateDashboardzoomroomTool(cfg),
		tools_devices.CreateDevicelistTool(cfg),
		tools_devices.CreateDevicecreateTool(cfg),
		tools_roles.CreateRolemembersTool(cfg),
		tools_roles.CreateAddrolemembersTool(cfg),
		tools_phone_shared_line_groups.CreateAssignphonenumbersslgTool(cfg),
		tools_rooms.CreateGetzrsettingsTool(cfg),
		tools_rooms.CreateUpdatezrsettingsTool(cfg),
		tools_webinars.CreateWebinarstatusTool(cfg),
		tools_webinars.CreateGettrackingsourcesTool(cfg),
		tools_phone_blocked_list.CreateListblockedlistTool(cfg),
		tools_phone_blocked_list.CreateAddanumbertoblockedlistTool(cfg),
		tools_cloud_recording.CreateRecordingdeleteoneTool(cfg),
		tools_groups.CreateGetgroupsettingsTool(cfg),
		tools_groups.CreateUpdategroupsettingsTool(cfg),
		tools_users.CreateUserschedulersdeleteTool(cfg),
		tools_users.CreateUserschedulersTool(cfg),
		tools_reports.CreateReporttelephoneTool(cfg),
		tools_dashboards.CreateDashboardmeetingsTool(cfg),
		tools_cloud_recording.CreateRecordingstatusupdateoneTool(cfg),
		tools_sip_connected_audio.CreateAssignsipconfigTool(cfg),
		tools_cloud_recording.CreateRecordingstatusupdateTool(cfg),
		tools_rooms_location.CreateGetzrlocationstructureTool(cfg),
		tools_rooms_location.CreateUpdatezoomroomslocationstructureTool(cfg),
		tools_sip_connected_audio.CreateDeleteinternalnumberTool(cfg),
		tools_groups.CreateGroupdeleteTool(cfg),
		tools_groups.CreateGroupTool(cfg),
		tools_groups.CreateGroupupdateTool(cfg),
		tools_chat_channels.CreateRemoveauserlevelchannelmemberTool(cfg),
		tools_dashboards.CreateParticipantwebinarfeedbackTool(cfg),
		tools_meetings.CreateCreatebatchpollsTool(cfg),
		tools_rooms.CreateManagee911signageTool(cfg),
		tools_chatbot_messages.CreateDeleteachatbotmessageTool(cfg),
		tools_chatbot_messages.CreateEditchatbotmessageTool(cfg),
		tools_phone_call_queues.CreateUpdatecallqueueTool(cfg),
		tools_phone_call_queues.CreateDeleteacallqueueTool(cfg),
		tools_phone_call_queues.CreateGetacallqueueTool(cfg),
		tools_meetings.CreateMeetingregistrantsquestionsgetTool(cfg),
		tools_meetings.CreateMeetingregistrantquestionupdateTool(cfg),
		tools_contacts.CreateSearchcompanycontactsTool(cfg),
		tools_roles.CreateGetroleinformationTool(cfg),
		tools_roles.CreateUpdateroleTool(cfg),
		tools_roles.CreateDeleteroleTool(cfg),
		tools_roles.CreateRolememberdeleteTool(cfg),
		tools_webinars.CreateListwebinartemplatesTool(cfg),
		tools_phone.CreateAssignphonenumberTool(cfg),
		tools_users.CreateUseremailupdateTool(cfg),
		tools_tsp.CreateTspTool(cfg),
		tools_tsp.CreateTspupdateTool(cfg),
		tools_phone_blocked_list.CreateDeleteablockedlistTool(cfg),
		tools_phone_blocked_list.CreateGetablockedlistTool(cfg),
		tools_phone_blocked_list.CreateUpdateblockedlistTool(cfg),
		tools_phone.CreateListbyocsiptrunkTool(cfg),
		tools_meetings.CreatePastmeetingparticipantsTool(cfg),
		tools_users.CreateUservanitynameTool(cfg),
		tools_dashboards.CreateDashboardmeetingparticipantsTool(cfg),
		tools_users.CreateUserpermissionTool(cfg),
		tools_billing.CreateDownloadinvoicepdfTool(cfg),
		tools_users.CreateUsersettingsTool(cfg),
		tools_users.CreateUsersettingsupdateTool(cfg),
		tools_rooms_devices.CreateChangezoomroomsappversionTool(cfg),
		tools_trackingfield.CreateTrackingfielddeleteTool(cfg),
		tools_trackingfield.CreateTrackingfieldgetTool(cfg),
		tools_trackingfield.CreateTrackingfieldupdateTool(cfg),
		tools_tsp.CreateUsertspsTool(cfg),
		tools_tsp.CreateUsertspcreateTool(cfg),
		tools_cloud_recording.CreateListarchivedfilesTool(cfg),
		tools_rooms_location.CreateListzrlocationsTool(cfg),
		tools_rooms_location.CreateAddazrlocationTool(cfg),
		tools_accounts.CreateDelvbTool(cfg),
		tools_webinars.CreateListpastwebinarqaTool(cfg),
		tools_webinars.CreateAddbatchwebinarregistrantsTool(cfg),
		tools_phone_site.CreateDeletephonesiteTool(cfg),
		tools_phone_site.CreateGetasiteTool(cfg),
		tools_phone_site.CreateUpdatesitedetailsTool(cfg),
		tools_webinars.CreatePastwebinarsTool(cfg),
		tools_cloud_recording.CreateMeetingrecordingregistrantcreateTool(cfg),
		tools_cloud_recording.CreateMeetingrecordingregistrantsTool(cfg),
		tools_users.CreateUserdeleteTool(cfg),
		tools_users.CreateUserTool(cfg),
		tools_users.CreateUserupdateTool(cfg),
		tools_phone.CreateUnassigncallingplanTool(cfg),
		tools_phone.CreateGetphonerecordingsTool(cfg),
		tools_rooms_location.CreateGetzrlocationprofileTool(cfg),
		tools_rooms_location.CreateUpdatezrlocationprofileTool(cfg),
		tools_users.CreateUserssotokendeleteTool(cfg),
		tools_users.CreateUsertokenTool(cfg),
		tools_rooms_location.CreateGetzrlocationsettingsTool(cfg),
		tools_rooms_location.CreateUpdatezrlocationsettingsTool(cfg),
		tools_webinars.CreateListwebinarparticipantsTool(cfg),
		tools_contacts.CreateGetusercontactTool(cfg),
		tools_reports.CreateReportwebinarqaTool(cfg),
		tools_accounts.CreateAccountsettingsTool(cfg),
		tools_accounts.CreateAccountsettingsupdateTool(cfg),
		tools_phone.CreateDeletevoicemailTool(cfg),
		tools_phone.CreateAddbyocnumberTool(cfg),
		tools_rooms.CreateCheckinroomsTool(cfg),
		tools_deprecated_api_endpoints.CreateListpastmeetingfilesTool(cfg),
		tools_dashboards.CreateDashboardclientfeedbackdetailTool(cfg),
		tools_webinars.CreateWebinarpollsTool(cfg),
		tools_webinars.CreateWebinarpollcreateTool(cfg),
		tools_chat_channels_account_level.CreateDeletechannelTool(cfg),
		tools_chat_channels_account_level.CreateGetchannelTool(cfg),
		tools_chat_channels_account_level.CreateUpdatechannelTool(cfg),
		tools_phone_reports.CreateGetpsoperationlogsTool(cfg),
		tools_sip_connected_audio.CreateListsiptrunksTool(cfg),
		tools_sip_connected_audio.CreateAssignsiptrunksTool(cfg),
		tools_chatbot_messages.CreateSendchatbotTool(cfg),
		tools_billing.CreateAccountplanbasedeleteTool(cfg),
		tools_dashboards.CreateDashboardwebinarparticipantqosTool(cfg),
		tools_tsp.CreateTspurlupdateTool(cfg),
		tools_phone.CreatePhoneuserTool(cfg),
		tools_phone.CreateUpdateuserprofileTool(cfg),
		tools_phone.CreateAccountcalllogsTool(cfg),
		tools_accounts.CreateAccounttrusteddomainTool(cfg),
		tools_dashboards.CreateGetcallqosTool(cfg),
		tools_meetings.CreateMeetingupdateTool(cfg),
		tools_meetings.CreateMeetingdeleteTool(cfg),
		tools_meetings.CreateMeetingTool(cfg),
		tools_phone_shared_line_groups.CreateListsharedlinegroupsTool(cfg),
		tools_phone_shared_line_groups.CreateCreateasharedlinegroupTool(cfg),
		tools_accounts.CreateAccountdisassociateTool(cfg),
		tools_accounts.CreateAccountTool(cfg),
		tools_phone.CreatePhoneuservoicemailsTool(cfg),
		tools_phone.CreatePostphonesiptrunkTool(cfg),
		tools_groups.CreateGetgrouplocksettingsTool(cfg),
		tools_groups.CreateGrouplockedsettingsTool(cfg),
		tools_dashboards.CreateDashboardzoomroomissueTool(cfg),
		tools_common_area_phones.CreateGetacommonareaphoneTool(cfg),
		tools_common_area_phones.CreateUpdatecommonareaphoneTool(cfg),
		tools_common_area_phones.CreateDeletecommonareaphoneTool(cfg),
		tools_cloud_recording.CreateRecordingregistrantquestionupdateTool(cfg),
		tools_cloud_recording.CreateRecordingregistrantsquestionsgetTool(cfg),
		tools_phone_call_queues.CreateUnassignphonenumcallqueueTool(cfg),
		tools_im_chat.CreateListimmessagesTool(cfg),
		tools_groups.CreateGroupmembersTool(cfg),
		tools_groups.CreateGroupmemberscreateTool(cfg),
		tools_reports.CreateReportwebinarpollsTool(cfg),
		tools_rooms_location.CreateChangeparentlocationTool(cfg),
		tools_phone.CreatePhoneuserrecordingsTool(cfg),
		tools_reports.CreateReportwebinarparticipantsTool(cfg),
		tools_chat_channels.CreateCreatechannelTool(cfg),
		tools_chat_channels.CreateGetchannelsTool(cfg),
		tools_reports.CreateReportmeetingsTool(cfg),
		tools_dashboards.CreateListcalllogsmetricsTool(cfg),
		tools_sip_phone.CreateDeletesipphoneTool(cfg),
		tools_sip_phone.CreateUpdatesipphoneTool(cfg),
		tools_reports.CreateReportusersTool(cfg),
		tools_phone.CreateSetupaccountTool(cfg),
		tools_sip_connected_audio.CreateListsiptrunknumbersTool(cfg),
		tools_billing.CreateAccountbillinginvoicesTool(cfg),
		tools_billing.CreateAccountplanaddoncreateTool(cfg),
		tools_billing.CreateAccountplanaddonupdateTool(cfg),
		tools_phone.CreateUpdatephonesiptrunkTool(cfg),
		tools_dashboards.CreateDashboardclientfeedbackTool(cfg),
		tools_sip_connected_audio.CreateDeleteinternalcalloutcountryTool(cfg),
		tools_chat_channels_account_level.CreateListchannelmembersTool(cfg),
		tools_chat_channels_account_level.CreateInvitechannelmembersTool(cfg),
		tools_reports.CreateReportcloudrecordingTool(cfg),
		tools_webinars.CreateWebinarupdateTool(cfg),
		tools_webinars.CreateWebinardeleteTool(cfg),
		tools_webinars.CreateWebinarTool(cfg),
		tools_billing.CreateAccountplanbaseupdateTool(cfg),
		tools_phone.CreatePhoneusercalllogsTool(cfg),
		tools_phone.CreateListphoneusersTool(cfg),
		tools_webinars.CreateWebinarsTool(cfg),
		tools_webinars.CreateWebinarcreateTool(cfg),
		tools_webinars.CreateWebinarregistrantsquestionsgetTool(cfg),
		tools_webinars.CreateWebinarregistrantquestionupdateTool(cfg),
		tools_accounts.CreateUpdateaccountownerTool(cfg),
		tools_meetings.CreateMeetingsTool(cfg),
		tools_meetings.CreateMeetingcreateTool(cfg),
		tools_sip_connected_audio.CreateDeleteallsipnumbersTool(cfg),
		tools_sip_connected_audio.CreateAssignsiptrunknumbersTool(cfg),
		tools_common_area_phones.CreateListcommonareaphonesTool(cfg),
		tools_common_area_phones.CreateAddcommonareaphoneTool(cfg),
		tools_webinars.CreateWebinarpanelistdeleteTool(cfg),
		tools_phone.CreatePhoneusersettingsTool(cfg),
		tools_im_chat.CreateImchatsessionsTool(cfg),
		tools_webinars.CreateWebinarregistrantsTool(cfg),
		tools_webinars.CreateWebinarregistrantcreateTool(cfg),
		tools_groups.CreateDelgroupvbTool(cfg),
		tools_meetings.CreateMeetingregistrantstatusTool(cfg),
		tools_webinars.CreateWebinarpollupdateTool(cfg),
		tools_webinars.CreateWebinarpolldeleteTool(cfg),
		tools_webinars.CreateWebinarpollgetTool(cfg),
		tools_phone.CreateAddsettingtemplateTool(cfg),
		tools_phone.CreateListsettingtemplatesTool(cfg),
		tools_sip_connected_audio.CreateListinternalcalloutcountriesTool(cfg),
		tools_sip_connected_audio.CreateAddcalloutcountriesTool(cfg),
		tools_users.CreateDeluservbTool(cfg),
		tools_dashboards.CreateDashboardwebinarsTool(cfg),
		tools_meetings.CreateMeetingregistrantsTool(cfg),
		tools_meetings.CreateMeetingregistrantcreateTool(cfg),
		tools_dashboards.CreateDashboardimTool(cfg),
		tools_meetings.CreateGetlivestreamdetailsTool(cfg),
		tools_meetings.CreateMeetinglivestreamupdateTool(cfg),
		tools_dashboards.CreateDashboardwebinarparticipantshareTool(cfg),
		tools_meetings.CreatePastmeetingsTool(cfg),
		tools_phone_call_queues.CreateUnassignmemberfromcallqueueTool(cfg),
		tools_users.CreateUserassistantdeleteTool(cfg),
		tools_dashboards.CreateDashboardwebinarparticipantsqosTool(cfg),
		tools_billing.CreateAccountplanaddoncancelTool(cfg),
		tools_users.CreateUserschedulerdeleteTool(cfg),
		tools_billing.CreateGetaccountbillinginvoiceTool(cfg),
		tools_webinars.CreateWebinarabsenteesTool(cfg),
		tools_pac.CreateUserpacsTool(cfg),
		tools_phone_shared_line_groups.CreateDeletemembersofslgTool(cfg),
		tools_phone_shared_line_groups.CreateAddmemberstosharedlinegroupTool(cfg),
		tools_phone_devices.CreateGetadeviceTool(cfg),
		tools_phone_devices.CreateUpdateadeviceTool(cfg),
		tools_phone_devices.CreateDeleteadeviceTool(cfg),
		tools_im_groups.CreateImgroupmembersTool(cfg),
		tools_im_groups.CreateImgroupmemberscreateTool(cfg),
		tools_chat_channels.CreateDeleteuserlevelchannelTool(cfg),
		tools_chat_channels.CreateGetuserlevelchannelTool(cfg),
		tools_chat_channels.CreateUpdateuserlevelchannelTool(cfg),
		tools_accounts.CreateGetaccountlocksettingsTool(cfg),
		tools_accounts.CreateUpdateaccountlocksettingsTool(cfg),
		tools_rooms_account.CreateGetzraccountsettingsTool(cfg),
		tools_rooms_account.CreateUpdatezoomroomaccsettingsTool(cfg),
		tools_reports.CreateReportwebinardetailsTool(cfg),
		tools_reports.CreateReportmeetingdetailsTool(cfg),
		tools_phone.CreateListaccountphonenumbersTool(cfg),
		tools_users.CreateUserzakTool(cfg),
		tools_im_groups.CreateImgroupmembersdeleteTool(cfg),
		tools_webinars.CreateWebinarpanelistsTool(cfg),
		tools_webinars.CreateWebinarpanelistcreateTool(cfg),
		tools_webinars.CreateWebinarpanelistsdeleteTool(cfg),
		tools_phone.CreateChangemaincompanynumberTool(cfg),
		tools_meetings.CreateInmeetingrecordingcontrolTool(cfg),
		tools_accounts.CreateAccountsTool(cfg),
		tools_accounts.CreateAccountcreateTool(cfg),
		tools_groups.CreateGroupsTool(cfg),
		tools_groups.CreateGroupcreateTool(cfg),
		tools_dashboards.CreateDashboardissuezoomroomTool(cfg),
		tools_reports.CreateReportsigninsignoutactivitiesTool(cfg),
		tools_cloud_recording.CreateRecordingsettingupdateTool(cfg),
		tools_cloud_recording.CreateRecordingsettingsupdateTool(cfg),
		tools_devices.CreateDevicedeleteTool(cfg),
		tools_devices.CreateDeviceupdateTool(cfg),
		tools_phone_call_queues.CreateUnassignallmembersTool(cfg),
		tools_phone_call_queues.CreateAddmemberstocallqueueTool(cfg),
		tools_phone.CreateListcallingplansTool(cfg),
		tools_meetings.CreateMeetingstatusTool(cfg),
		tools_billing.CreateAccountbillingTool(cfg),
		tools_billing.CreateAccountbillingupdateTool(cfg),
		tools_meetings.CreateListpastmeetingpollsTool(cfg),
		tools_im_chat.CreateImchatmessagesTool(cfg),
		tools_meetings.CreateMeetinginvitationTool(cfg),
		tools_phone.CreateUpdatephonesettingsTool(cfg),
		tools_trackingfield.CreateTrackingfieldlistTool(cfg),
		tools_trackingfield.CreateTrackingfieldcreateTool(cfg),
		tools_phone_shared_line_groups.CreateDeleteaphonenumberslgTool(cfg),
		tools_users.CreateUserpasswordTool(cfg),
		tools_meetings.CreateMeetingpollcreateTool(cfg),
		tools_meetings.CreateMeetingpollsTool(cfg),
		tools_rooms.CreateListdigitalsignagecontentTool(cfg),
		tools_chat_channels.CreateLeavechannelTool(cfg),
		tools_chat_channels.CreateJoinchannelTool(cfg),
		tools_dashboards.CreateDashboardmeetingparticipantshareTool(cfg),
		tools_dashboards.CreateDashboardmeetingparticipantsqosTool(cfg),
		tools_phone_auto_receptionists.CreateUpdateautoreceptionistTool(cfg),
		tools_phone_call_queues.CreateListcallqueuesTool(cfg),
		tools_phone_call_queues.CreateCreatecallqueueTool(cfg),
		tools_billing.CreateGetplanusageTool(cfg),
		tools_users.CreateUsersTool(cfg),
		tools_users.CreateUsercreateTool(cfg),
		tools_users.CreateUserassistantsdeleteTool(cfg),
		tools_users.CreateUserassistantsTool(cfg),
		tools_users.CreateUserassistantcreateTool(cfg),
		tools_phone.CreateDeletecalllogTool(cfg),
		tools_chat_channels_account_level.CreateRemoveachannelmemberTool(cfg),
		tools_accounts.CreateAccountoptionsupdateTool(cfg),
		tools_phone_call_queues.CreateGetcallqueuerecordingsTool(cfg),
		tools_deprecated_api_endpoints.CreateListpastwebinarfilesTool(cfg),
		tools_dashboards.CreateDashboardissuedetailzoomroomTool(cfg),
		tools_phone_call_queues.CreateChangecallqueuemanagerTool(cfg),
		tools_phone_auto_receptionists.CreateAddautoreceptionistTool(cfg),
		tools_users.CreateUserstatusTool(cfg),
		tools_phone_site.CreateListphonesitesTool(cfg),
		tools_phone_site.CreateCreatephonesiteTool(cfg),
		tools_phone.CreateAssigncallingplanTool(cfg),
		tools_users.CreateUseremailTool(cfg),
		tools_meetings.CreatePastmeetingdetailsTool(cfg),
		tools_reports.CreateReportdailyTool(cfg),
		tools_phone_call_queues.CreateUnassignaphonenumcallqueueTool(cfg),
		tools_phone_call_queues.CreateAssignphonetocallqueueTool(cfg),
		tools_dashboards.CreateDashboardcrcTool(cfg),
	}
}
